### ISSUE TITLE
不支持支持Profiling, 原因不明

### ISSUE THREAD

**Issue by wjxforu** [ivan-94/taro-plugin-react-devtools#1]
profiling support requires either a development or production-profiling build of react v16.5+

![Snipaste_2021-10-14_09-25-47](https://user-images.githubusercontent.com/7859666/137234890-7c613ef7-1af7-4704-830c-9b161c047305.png)

环境: 
"@tarojs/plugin-react-devtools": "^3.3.9",
"@tarojs/components": "3.3.9",
"@tarojs/react": "3.3.9",
"@tarojs/runtime": "3.3.9",
"@tarojs/taro": "3.3.9",
"react": "^17.0.0",
"react-dom": "^17.0.0",

因为比较新手, 不太清楚怎么才能支持到. 所以提了个issue. 感谢.

本身是dev build的. 所以不存在production的情况. 

修改的配置如下: 
![Snipaste_2021-10-14_09-36-45](https://user-images.githubusercontent.com/7859666/137235865-3e3e5c52-f51b-4255-bcc0-12f66be17bdf.png)

**Comment by ivan-94** [comment]
taro 官方已经支持 devtools 了，你可以试下官方可不可以，给 taro提issue


发自我的iPhone

在 2021年10月14日，上午9:35，wjxforu ***@***.***> 写道：

﻿

profiling support requires either a development or production-profiling build of react v16.5+

[Snipaste_2021-10-14_09-25-47]<https://user-images.githubusercontent.com/7859666/137234890-7c613ef7-1af7-4704-830c-9b161c047305.png>

环境:
***@***.***/plugin-react-devtools": "^3.3.9",
***@***.***/components": "3.3.9",
***@***.***/react": "3.3.9",
***@***.***/runtime": "3.3.9",
***@***.***/taro": "3.3.9",
"react": "^17.0.0",
"react-dom": "^17.0.0",

因为比较新手, 不太清楚怎么才能支持到. 所以提了个issue. 感谢.

**Comment by wjxforu** [comment]
感谢哈..我发现发其实我用的就是官方的版本..

taro-plugin-react-devtools vs plugin-react-devtools

不好意思, 闹乌龙了. 感谢回复

**Comment by peacejj** [comment]
@wjxforu  求问你怎么使用的Profiling，我也是用的官方的@tarojs/plugin-react-devtools，但是Profiling不能用，报:profiling support requires either a development or production-profiling build of react v16.5+
